### ISSUE TITLE
xcode 5 storyboard UIRefreshControl error

### ISSUE THREAD

**Issue by ronalddewaal** [instructure/CKRefreshControl#24]
Using the UIRefreshControl directly in a storyboard triggers the following error in xCode5:

..../CKRefreshControl/RefreshControlDemo/en.lproj/MainStoryboard.storyboard: error: Class Unavailable: UIRefreshControl on iOS versions prior to 6.0

Adding the control programmatically still works fine.
But the Demo project on 1.1.1 has this error with the latest xCode 5.0

**Comment by simonista** [comment]
Closing out old issues in preparation to archive this project.
